Updating version of Jackson because of an error
Using 2.7.0 I get an error between you library and java library for bots where is the version of Jackson 2.8.7: 
exception in thread "main" java.lang.NoSuchMethodError: com.fasterxml.jackson.core.JsonGenerator.writeStartObject(Ljava/lang/Object;)V 
but when I specify explicitly in my own POM file version higher than 2.8.0, all is ok.